// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_lastDrawPanel;
lv_obj_t * ui_numberPanel;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_number;
lv_obj_t * ui_numberPanel1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_number1;
lv_obj_t * ui_numberPanel2;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_number2;
lv_obj_t * ui_numberPanel3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_number3;
lv_obj_t * ui_numberPanel4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_number4;
lv_obj_t * ui_numberPanel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_number5;
lv_obj_t * ui_numberPanel6;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_number6;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_scoreLbl;
lv_obj_t * ui_Label6;
lv_obj_t * ui_noDevicesLbl;
lv_obj_t * ui_Label8;
lv_obj_t * ui_msg;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_numWinings;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_numWinings1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_numWinings2;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_numWinings3;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_numWinings4;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_numWinings5;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_totalGames;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_myNumber1;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_myNumber2;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_myNumber3;
lv_obj_t * ui_Panel19;
lv_obj_t * ui_myNumber4;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_myNumber5;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_myNumber6;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_myNumber7;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_Panel27;
void ui_event_choseNumbersPanel(lv_event_t * e);
lv_obj_t * ui_choseNumbersPanel;
lv_obj_t * ui_Label18;
void ui_event_GOrULES(lv_event_t * e);
lv_obj_t * ui_GOrULES;
lv_obj_t * ui_InitPanel;
lv_obj_t * ui_initMsg;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panel28;
void ui_event_numPan1(lv_event_t * e);
lv_obj_t * ui_numPan1;
lv_obj_t * ui_myCH1;
void ui_event_numPan2(lv_event_t * e);
lv_obj_t * ui_numPan2;
lv_obj_t * ui_myCH2;
void ui_event_numPan3(lv_event_t * e);
lv_obj_t * ui_numPan3;
lv_obj_t * ui_myCH3;
void ui_event_numPan4(lv_event_t * e);
lv_obj_t * ui_numPan4;
lv_obj_t * ui_myCH4;
void ui_event_numPan5(lv_event_t * e);
lv_obj_t * ui_numPan5;
lv_obj_t * ui_myCH5;
void ui_event_numPan6(lv_event_t * e);
lv_obj_t * ui_numPan6;
lv_obj_t * ui_myCH6;
void ui_event_numPan7(lv_event_t * e);
lv_obj_t * ui_numPan7;
lv_obj_t * ui_myCH7;
void ui_event_numPan8(lv_event_t * e);
lv_obj_t * ui_numPan8;
lv_obj_t * ui_myCH8;
void ui_event_numPan9(lv_event_t * e);
lv_obj_t * ui_numPan9;
lv_obj_t * ui_myCH9;
void ui_event_numPan10(lv_event_t * e);
lv_obj_t * ui_numPan10;
lv_obj_t * ui_myCH10;
void ui_event_numPan11(lv_event_t * e);
lv_obj_t * ui_numPan11;
lv_obj_t * ui_myCH11;
void ui_event_numPan12(lv_event_t * e);
lv_obj_t * ui_numPan12;
lv_obj_t * ui_myCH12;
void ui_event_numPan13(lv_event_t * e);
lv_obj_t * ui_numPan13;
lv_obj_t * ui_myCH13;
void ui_event_numPan14(lv_event_t * e);
lv_obj_t * ui_numPan14;
lv_obj_t * ui_myCH14;
void ui_event_numPan15(lv_event_t * e);
lv_obj_t * ui_numPan15;
lv_obj_t * ui_myCH15;
void ui_event_numPan16(lv_event_t * e);
lv_obj_t * ui_numPan16;
lv_obj_t * ui_myCH16;
lv_obj_t * ui_Panel29;
void ui_event_numPan17(lv_event_t * e);
lv_obj_t * ui_numPan17;
lv_obj_t * ui_myCH17;
void ui_event_numPan18(lv_event_t * e);
lv_obj_t * ui_numPan18;
lv_obj_t * ui_myCH18;
void ui_event_numPan19(lv_event_t * e);
lv_obj_t * ui_numPan19;
lv_obj_t * ui_myCH19;
void ui_event_numPan20(lv_event_t * e);
lv_obj_t * ui_numPan20;
lv_obj_t * ui_myCH20;
void ui_event_numPan21(lv_event_t * e);
lv_obj_t * ui_numPan21;
lv_obj_t * ui_myCH21;
void ui_event_numPan22(lv_event_t * e);
lv_obj_t * ui_numPan22;
lv_obj_t * ui_myCH22;
void ui_event_numPan23(lv_event_t * e);
lv_obj_t * ui_numPan23;
lv_obj_t * ui_myCH23;
void ui_event_numPan24(lv_event_t * e);
lv_obj_t * ui_numPan24;
lv_obj_t * ui_myCH24;
void ui_event_numPan25(lv_event_t * e);
lv_obj_t * ui_numPan25;
lv_obj_t * ui_myCH25;
void ui_event_numPan26(lv_event_t * e);
lv_obj_t * ui_numPan26;
lv_obj_t * ui_myCH26;
void ui_event_numPan27(lv_event_t * e);
lv_obj_t * ui_numPan27;
lv_obj_t * ui_myCH27;
void ui_event_numPan28(lv_event_t * e);
lv_obj_t * ui_numPan28;
lv_obj_t * ui_myCH28;
void ui_event_numPan29(lv_event_t * e);
lv_obj_t * ui_numPan29;
lv_obj_t * ui_myCH29;
void ui_event_numPan30(lv_event_t * e);
lv_obj_t * ui_numPan30;
lv_obj_t * ui_myCH30;
void ui_event_numPan31(lv_event_t * e);
lv_obj_t * ui_numPan31;
lv_obj_t * ui_myCH31;
void ui_event_numPan32(lv_event_t * e);
lv_obj_t * ui_numPan32;
lv_obj_t * ui_myCH32;
lv_obj_t * ui_Panel30;
void ui_event_numPan33(lv_event_t * e);
lv_obj_t * ui_numPan33;
lv_obj_t * ui_myCH33;
void ui_event_numPan34(lv_event_t * e);
lv_obj_t * ui_numPan34;
lv_obj_t * ui_myCH34;
void ui_event_numPan35(lv_event_t * e);
lv_obj_t * ui_numPan35;
lv_obj_t * ui_myCH35;
void ui_event_numPan36(lv_event_t * e);
lv_obj_t * ui_numPan36;
lv_obj_t * ui_myCH36;
void ui_event_numPan37(lv_event_t * e);
lv_obj_t * ui_numPan37;
lv_obj_t * ui_myCH37;
void ui_event_numPan38(lv_event_t * e);
lv_obj_t * ui_numPan38;
lv_obj_t * ui_myCH38;
void ui_event_numPan39(lv_event_t * e);
lv_obj_t * ui_numPan39;
lv_obj_t * ui_myCH39;
void ui_event_numPan40(lv_event_t * e);
lv_obj_t * ui_numPan40;
lv_obj_t * ui_myCH40;
void ui_event_numPan41(lv_event_t * e);
lv_obj_t * ui_numPan41;
lv_obj_t * ui_myCH41;
void ui_event_numPan42(lv_event_t * e);
lv_obj_t * ui_numPan42;
lv_obj_t * ui_myCH42;
void ui_event_numPan43(lv_event_t * e);
lv_obj_t * ui_numPan43;
lv_obj_t * ui_myCH43;
void ui_event_numPan44(lv_event_t * e);
lv_obj_t * ui_numPan44;
lv_obj_t * ui_myCH44;
void ui_event_numPan45(lv_event_t * e);
lv_obj_t * ui_numPan45;
lv_obj_t * ui_myCH45;
void ui_event_numPan46(lv_event_t * e);
lv_obj_t * ui_numPan46;
lv_obj_t * ui_myCH46;
void ui_event_numPan47(lv_event_t * e);
lv_obj_t * ui_numPan47;
lv_obj_t * ui_myCH47;
void ui_event_numPan48(lv_event_t * e);
lv_obj_t * ui_numPan48;
lv_obj_t * ui_myCH48;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label15;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel31;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Panel32;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel33;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel34;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel35;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Panel36;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Panel37;
lv_obj_t * ui_Label25;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_choseNumbersPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen2_screen_init);
        resetAll(e);
    }
}
void ui_event_GOrULES(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}
void ui_event_numPan1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan21(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan25(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan26(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan28(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan29(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan30(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan32(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan34(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan35(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan36(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan37(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan38(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan39(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan40(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan41(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan42(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan43(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan44(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan45(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan46(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan47(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_numPan48(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        choseNumber(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
        saveNumbers(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
