// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_lastDrawPanel;
extern lv_obj_t * ui_numberPanel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_number;
extern lv_obj_t * ui_numberPanel1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_number1;
extern lv_obj_t * ui_numberPanel2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_number2;
extern lv_obj_t * ui_numberPanel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_number3;
extern lv_obj_t * ui_numberPanel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_number4;
extern lv_obj_t * ui_numberPanel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_number5;
extern lv_obj_t * ui_numberPanel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_number6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_scoreLbl;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_noDevicesLbl;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_msg;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_numWinings;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_numWinings1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_numWinings2;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_numWinings3;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_numWinings4;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_numWinings5;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_totalGames;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_myNumber1;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_myNumber2;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_myNumber3;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_myNumber4;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_myNumber5;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_myNumber6;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_myNumber7;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Panel27;
void ui_event_choseNumbersPanel(lv_event_t * e);
extern lv_obj_t * ui_choseNumbersPanel;
extern lv_obj_t * ui_Label18;
void ui_event_GOrULES(lv_event_t * e);
extern lv_obj_t * ui_GOrULES;
extern lv_obj_t * ui_InitPanel;
extern lv_obj_t * ui_initMsg;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel28;
void ui_event_numPan1(lv_event_t * e);
extern lv_obj_t * ui_numPan1;
extern lv_obj_t * ui_myCH1;
void ui_event_numPan2(lv_event_t * e);
extern lv_obj_t * ui_numPan2;
extern lv_obj_t * ui_myCH2;
void ui_event_numPan3(lv_event_t * e);
extern lv_obj_t * ui_numPan3;
extern lv_obj_t * ui_myCH3;
void ui_event_numPan4(lv_event_t * e);
extern lv_obj_t * ui_numPan4;
extern lv_obj_t * ui_myCH4;
void ui_event_numPan5(lv_event_t * e);
extern lv_obj_t * ui_numPan5;
extern lv_obj_t * ui_myCH5;
void ui_event_numPan6(lv_event_t * e);
extern lv_obj_t * ui_numPan6;
extern lv_obj_t * ui_myCH6;
void ui_event_numPan7(lv_event_t * e);
extern lv_obj_t * ui_numPan7;
extern lv_obj_t * ui_myCH7;
void ui_event_numPan8(lv_event_t * e);
extern lv_obj_t * ui_numPan8;
extern lv_obj_t * ui_myCH8;
void ui_event_numPan9(lv_event_t * e);
extern lv_obj_t * ui_numPan9;
extern lv_obj_t * ui_myCH9;
void ui_event_numPan10(lv_event_t * e);
extern lv_obj_t * ui_numPan10;
extern lv_obj_t * ui_myCH10;
void ui_event_numPan11(lv_event_t * e);
extern lv_obj_t * ui_numPan11;
extern lv_obj_t * ui_myCH11;
void ui_event_numPan12(lv_event_t * e);
extern lv_obj_t * ui_numPan12;
extern lv_obj_t * ui_myCH12;
void ui_event_numPan13(lv_event_t * e);
extern lv_obj_t * ui_numPan13;
extern lv_obj_t * ui_myCH13;
void ui_event_numPan14(lv_event_t * e);
extern lv_obj_t * ui_numPan14;
extern lv_obj_t * ui_myCH14;
void ui_event_numPan15(lv_event_t * e);
extern lv_obj_t * ui_numPan15;
extern lv_obj_t * ui_myCH15;
void ui_event_numPan16(lv_event_t * e);
extern lv_obj_t * ui_numPan16;
extern lv_obj_t * ui_myCH16;
extern lv_obj_t * ui_Panel29;
void ui_event_numPan17(lv_event_t * e);
extern lv_obj_t * ui_numPan17;
extern lv_obj_t * ui_myCH17;
void ui_event_numPan18(lv_event_t * e);
extern lv_obj_t * ui_numPan18;
extern lv_obj_t * ui_myCH18;
void ui_event_numPan19(lv_event_t * e);
extern lv_obj_t * ui_numPan19;
extern lv_obj_t * ui_myCH19;
void ui_event_numPan20(lv_event_t * e);
extern lv_obj_t * ui_numPan20;
extern lv_obj_t * ui_myCH20;
void ui_event_numPan21(lv_event_t * e);
extern lv_obj_t * ui_numPan21;
extern lv_obj_t * ui_myCH21;
void ui_event_numPan22(lv_event_t * e);
extern lv_obj_t * ui_numPan22;
extern lv_obj_t * ui_myCH22;
void ui_event_numPan23(lv_event_t * e);
extern lv_obj_t * ui_numPan23;
extern lv_obj_t * ui_myCH23;
void ui_event_numPan24(lv_event_t * e);
extern lv_obj_t * ui_numPan24;
extern lv_obj_t * ui_myCH24;
void ui_event_numPan25(lv_event_t * e);
extern lv_obj_t * ui_numPan25;
extern lv_obj_t * ui_myCH25;
void ui_event_numPan26(lv_event_t * e);
extern lv_obj_t * ui_numPan26;
extern lv_obj_t * ui_myCH26;
void ui_event_numPan27(lv_event_t * e);
extern lv_obj_t * ui_numPan27;
extern lv_obj_t * ui_myCH27;
void ui_event_numPan28(lv_event_t * e);
extern lv_obj_t * ui_numPan28;
extern lv_obj_t * ui_myCH28;
void ui_event_numPan29(lv_event_t * e);
extern lv_obj_t * ui_numPan29;
extern lv_obj_t * ui_myCH29;
void ui_event_numPan30(lv_event_t * e);
extern lv_obj_t * ui_numPan30;
extern lv_obj_t * ui_myCH30;
void ui_event_numPan31(lv_event_t * e);
extern lv_obj_t * ui_numPan31;
extern lv_obj_t * ui_myCH31;
void ui_event_numPan32(lv_event_t * e);
extern lv_obj_t * ui_numPan32;
extern lv_obj_t * ui_myCH32;
extern lv_obj_t * ui_Panel30;
void ui_event_numPan33(lv_event_t * e);
extern lv_obj_t * ui_numPan33;
extern lv_obj_t * ui_myCH33;
void ui_event_numPan34(lv_event_t * e);
extern lv_obj_t * ui_numPan34;
extern lv_obj_t * ui_myCH34;
void ui_event_numPan35(lv_event_t * e);
extern lv_obj_t * ui_numPan35;
extern lv_obj_t * ui_myCH35;
void ui_event_numPan36(lv_event_t * e);
extern lv_obj_t * ui_numPan36;
extern lv_obj_t * ui_myCH36;
void ui_event_numPan37(lv_event_t * e);
extern lv_obj_t * ui_numPan37;
extern lv_obj_t * ui_myCH37;
void ui_event_numPan38(lv_event_t * e);
extern lv_obj_t * ui_numPan38;
extern lv_obj_t * ui_myCH38;
void ui_event_numPan39(lv_event_t * e);
extern lv_obj_t * ui_numPan39;
extern lv_obj_t * ui_myCH39;
void ui_event_numPan40(lv_event_t * e);
extern lv_obj_t * ui_numPan40;
extern lv_obj_t * ui_myCH40;
void ui_event_numPan41(lv_event_t * e);
extern lv_obj_t * ui_numPan41;
extern lv_obj_t * ui_myCH41;
void ui_event_numPan42(lv_event_t * e);
extern lv_obj_t * ui_numPan42;
extern lv_obj_t * ui_myCH42;
void ui_event_numPan43(lv_event_t * e);
extern lv_obj_t * ui_numPan43;
extern lv_obj_t * ui_myCH43;
void ui_event_numPan44(lv_event_t * e);
extern lv_obj_t * ui_numPan44;
extern lv_obj_t * ui_myCH44;
void ui_event_numPan45(lv_event_t * e);
extern lv_obj_t * ui_numPan45;
extern lv_obj_t * ui_myCH45;
void ui_event_numPan46(lv_event_t * e);
extern lv_obj_t * ui_numPan46;
extern lv_obj_t * ui_myCH46;
void ui_event_numPan47(lv_event_t * e);
extern lv_obj_t * ui_numPan47;
extern lv_obj_t * ui_myCH47;
void ui_event_numPan48(lv_event_t * e);
extern lv_obj_t * ui_numPan48;
extern lv_obj_t * ui_myCH48;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label15;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel31;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_table_png);    // assets\table.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
