// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lastDrawPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_lastDrawPanel, 514);
    lv_obj_set_height(ui_lastDrawPanel, 69);
    lv_obj_set_x(ui_lastDrawPanel, 0);
    lv_obj_set_y(ui_lastDrawPanel, -56);
    lv_obj_set_align(ui_lastDrawPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lastDrawPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lastDrawPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lastDrawPanel, lv_color_hex(0x05111C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lastDrawPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lastDrawPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel, 60);
    lv_obj_set_height(ui_numberPanel, 60);
    lv_obj_set_x(ui_numberPanel, -210);
    lv_obj_set_y(ui_numberPanel, 0);
    lv_obj_set_align(ui_numberPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_numberPanel);
    lv_obj_set_width(ui_Panel3, 38);
    lv_obj_set_height(ui_Panel3, 34);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number, "0");
    lv_obj_set_style_text_color(ui_number, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_number, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel1 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel1, 60);
    lv_obj_set_height(ui_numberPanel1, 60);
    lv_obj_set_x(ui_numberPanel1, -140);
    lv_obj_set_y(ui_numberPanel1, 0);
    lv_obj_set_align(ui_numberPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel1, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_numberPanel1);
    lv_obj_set_width(ui_Panel1, 38);
    lv_obj_set_height(ui_Panel1, 34);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_number1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number1, "0");
    lv_obj_set_style_text_color(ui_number1, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel2 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel2, 60);
    lv_obj_set_height(ui_numberPanel2, 60);
    lv_obj_set_x(ui_numberPanel2, -70);
    lv_obj_set_y(ui_numberPanel2, 0);
    lv_obj_set_align(ui_numberPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel2, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_numberPanel2);
    lv_obj_set_width(ui_Panel2, 38);
    lv_obj_set_height(ui_Panel2, 34);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_number2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number2, "0");
    lv_obj_set_style_text_color(ui_number2, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel3 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel3, 60);
    lv_obj_set_height(ui_numberPanel3, 60);
    lv_obj_set_align(ui_numberPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel3, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel3, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_numberPanel3);
    lv_obj_set_width(ui_Panel4, 38);
    lv_obj_set_height(ui_Panel4, 34);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_number3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number3, "0");
    lv_obj_set_style_text_color(ui_number3, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel4 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel4, 60);
    lv_obj_set_height(ui_numberPanel4, 60);
    lv_obj_set_x(ui_numberPanel4, 70);
    lv_obj_set_y(ui_numberPanel4, 0);
    lv_obj_set_align(ui_numberPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel4, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_numberPanel4);
    lv_obj_set_width(ui_Panel5, 38);
    lv_obj_set_height(ui_Panel5, 34);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number4 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_number4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number4, "0");
    lv_obj_set_style_text_color(ui_number4, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel5 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel5, 60);
    lv_obj_set_height(ui_numberPanel5, 60);
    lv_obj_set_x(ui_numberPanel5, 140);
    lv_obj_set_y(ui_numberPanel5, 0);
    lv_obj_set_align(ui_numberPanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel5, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel5, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_numberPanel5);
    lv_obj_set_width(ui_Panel6, 38);
    lv_obj_set_height(ui_Panel6, 34);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number5 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_number5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number5, "0");
    lv_obj_set_style_text_color(ui_number5, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number5, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numberPanel6 = lv_obj_create(ui_lastDrawPanel);
    lv_obj_set_width(ui_numberPanel6, 60);
    lv_obj_set_height(ui_numberPanel6, 60);
    lv_obj_set_x(ui_numberPanel6, 210);
    lv_obj_set_y(ui_numberPanel6, 0);
    lv_obj_set_align(ui_numberPanel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_numberPanel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numberPanel6, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numberPanel6, lv_color_hex(0x14BFD0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numberPanel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_numberPanel6);
    lv_obj_set_width(ui_Panel7, 38);
    lv_obj_set_height(ui_Panel7, 34);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_number6 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_number6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_number6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_number6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_number6, "0");
    lv_obj_set_style_text_color(ui_number6, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_number6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_number6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -182);
    lv_obj_set_y(ui_Label2, -105);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Lattest drawing:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xBDBABA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -181);
    lv_obj_set_y(ui_Label3, -4);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "BALANCE");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel24, 134);
    lv_obj_set_height(ui_Panel24, 47);
    lv_obj_set_x(ui_Panel24, -179);
    lv_obj_set_y(ui_Panel24, 74);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0x34083B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scoreLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_scoreLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scoreLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scoreLbl, -185);
    lv_obj_set_y(ui_scoreLbl, 27);
    lv_obj_set_align(ui_scoreLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scoreLbl, "0");
    lv_obj_set_style_text_font(ui_scoreLbl, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -184);
    lv_obj_set_y(ui_Label6, 61);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Devices");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_noDevicesLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_noDevicesLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_noDevicesLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_noDevicesLbl, -186);
    lv_obj_set_y(ui_noDevicesLbl, 83);
    lv_obj_set_align(ui_noDevicesLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_noDevicesLbl, "0");
    lv_obj_set_style_text_font(ui_noDevicesLbl, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -53);
    lv_obj_set_y(ui_Label8, -7);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "My Numbers");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x9F9B9B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_msg = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_msg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_msg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_msg, 20);
    lv_obj_set_y(ui_msg, 220);
    lv_label_set_text(ui_msg, "Welcome to Volos Lottery! Free and for fun!");
    lv_obj_set_style_text_color(ui_msg, lv_color_hex(0xA8B45C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_msg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 189);
    lv_obj_set_height(ui_Panel9, 115);
    lv_obj_set_x(ui_Panel9, 160);
    lv_obj_set_y(ui_Panel9, 42);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x410648), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 106);
    lv_obj_set_y(ui_Label7, -4);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "winings");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 87);
    lv_obj_set_y(ui_Label4, 22);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "x2");

    ui_Panel12 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel12, 52);
    lv_obj_set_height(ui_Panel12, 23);
    lv_obj_set_x(ui_Panel12, 127);
    lv_obj_set_y(ui_Panel12, 22);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_numWinings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings, "0");

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 171);
    lv_obj_set_y(ui_Label1, 22);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "x3");

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 52);
    lv_obj_set_height(ui_Panel13, 23);
    lv_obj_set_x(ui_Panel13, 213);
    lv_obj_set_y(ui_Panel13, 22);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings1 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_numWinings1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings1, "0");

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 87);
    lv_obj_set_y(ui_Label10, 52);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "x4");

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 87);
    lv_obj_set_y(ui_Label11, 82);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "x6");

    ui_Label12 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 171);
    lv_obj_set_y(ui_Label12, 52);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "x5");

    ui_Label13 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 173);
    lv_obj_set_y(ui_Label13, 82);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "x7");

    ui_Panel14 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel14, 52);
    lv_obj_set_height(ui_Panel14, 23);
    lv_obj_set_x(ui_Panel14, 127);
    lv_obj_set_y(ui_Panel14, 52);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings2 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_numWinings2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings2, "0");

    ui_Panel15 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel15, 52);
    lv_obj_set_height(ui_Panel15, 23);
    lv_obj_set_x(ui_Panel15, 213);
    lv_obj_set_y(ui_Panel15, 52);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings3 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_numWinings3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings3, "0");

    ui_Panel16 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel16, 52);
    lv_obj_set_height(ui_Panel16, 23);
    lv_obj_set_x(ui_Panel16, 127);
    lv_obj_set_y(ui_Panel16, 82);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings4 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_numWinings4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings4, "0");

    ui_Panel17 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel17, 52);
    lv_obj_set_height(ui_Panel17, 23);
    lv_obj_set_x(ui_Panel17, 213);
    lv_obj_set_y(ui_Panel17, 82);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xF26395), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numWinings5 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_numWinings5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_numWinings5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_numWinings5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_numWinings5, "0");

    ui_Label14 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 167);
    lv_obj_set_y(ui_Label14, 6);
    lv_label_set_text(ui_Label14, "Time");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x93A527), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider1, 0, 1900);
    lv_obj_set_width(ui_Slider1, 194);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 155);
    lv_obj_set_y(ui_Slider1, -104);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xF533F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_table_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 165
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Image1, -25);
    lv_obj_set_y(ui_Image1, 51);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 240);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 112);
    lv_obj_set_height(ui_Panel8, 20);
    lv_obj_set_x(ui_Panel8, 202);
    lv_obj_set_y(ui_Panel8, -5);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalGames = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_totalGames, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_totalGames, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_totalGames, 460);
    lv_obj_set_y(ui_totalGames, 108);
    lv_label_set_text(ui_totalGames, "0");
    lv_obj_set_style_text_color(ui_totalGames, lv_color_hex(0x93A527), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_totalGames, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel10, 32);
    lv_obj_set_height(ui_Panel10, 20);
    lv_obj_set_x(ui_Panel10, -77);
    lv_obj_set_y(ui_Panel10, 21);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber1 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_myNumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber1, "12");
    lv_obj_set_style_text_font(ui_myNumber1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 32);
    lv_obj_set_height(ui_Panel11, 20);
    lv_obj_set_x(ui_Panel11, -24);
    lv_obj_set_y(ui_Panel11, 21);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber2 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_myNumber2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber2, "12");
    lv_obj_set_style_text_font(ui_myNumber2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel18, 32);
    lv_obj_set_height(ui_Panel18, 20);
    lv_obj_set_x(ui_Panel18, 27);
    lv_obj_set_y(ui_Panel18, 21);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber3 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_myNumber3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber3, "12");
    lv_obj_set_style_text_font(ui_myNumber3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel19, 32);
    lv_obj_set_height(ui_Panel19, 20);
    lv_obj_set_x(ui_Panel19, -76);
    lv_obj_set_y(ui_Panel19, 51);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber4 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_myNumber4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber4, "12");
    lv_obj_set_style_text_font(ui_myNumber4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel20, 32);
    lv_obj_set_height(ui_Panel20, 20);
    lv_obj_set_x(ui_Panel20, -24);
    lv_obj_set_y(ui_Panel20, 51);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber5 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_myNumber5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber5, "12");
    lv_obj_set_style_text_font(ui_myNumber5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel21, 32);
    lv_obj_set_height(ui_Panel21, 20);
    lv_obj_set_x(ui_Panel21, 27);
    lv_obj_set_y(ui_Panel21, 51);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber6 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_myNumber6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber6, "12");
    lv_obj_set_style_text_font(ui_myNumber6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel22, 32);
    lv_obj_set_height(ui_Panel22, 20);
    lv_obj_set_x(ui_Panel22, -76);
    lv_obj_set_y(ui_Panel22, 81);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel22, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x0A2C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myNumber7 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_myNumber7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myNumber7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myNumber7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myNumber7, "12");
    lv_obj_set_style_text_font(ui_myNumber7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel23, 1);
    lv_obj_set_height(ui_Panel23, 127);
    lv_obj_set_x(ui_Panel23, -254);
    lv_obj_set_y(ui_Panel23, 50);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x13717D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel25, 406);
    lv_obj_set_height(ui_Panel25, 3);
    lv_obj_set_x(ui_Panel25, 45);
    lv_obj_set_y(ui_Panel25, -21);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel25, lv_color_hex(0x0A2542), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel26 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel26, 100);
    lv_obj_set_height(ui_Panel26, 6);
    lv_obj_set_x(ui_Panel26, 204);
    lv_obj_set_y(ui_Panel26, 110);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel26, lv_color_hex(0x58BD27), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel27 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel27, 406);
    lv_obj_set_height(ui_Panel27, 3);
    lv_obj_set_x(ui_Panel27, -50);
    lv_obj_set_y(ui_Panel27, -92);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel27, lv_color_hex(0x0A2542), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choseNumbersPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_choseNumbersPanel, 153);
    lv_obj_set_height(ui_choseNumbersPanel, 92);
    lv_obj_set_x(ui_choseNumbersPanel, -24);
    lv_obj_set_y(ui_choseNumbersPanel, 51);
    lv_obj_set_align(ui_choseNumbersPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_choseNumbersPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_choseNumbersPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choseNumbersPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_choseNumbersPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 168);
    lv_obj_set_y(ui_Label18, -5);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Game:");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GOrULES = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_GOrULES, 183);
    lv_obj_set_height(ui_GOrULES, 89);
    lv_obj_set_x(ui_GOrULES, 160);
    lv_obj_set_y(ui_GOrULES, 51);
    lv_obj_set_align(ui_GOrULES, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GOrULES, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GOrULES, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GOrULES, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GOrULES, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InitPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_InitPanel, 451);
    lv_obj_set_height(ui_InitPanel, 184);
    lv_obj_set_x(ui_InitPanel, 1);
    lv_obj_set_y(ui_InitPanel, 3);
    lv_obj_set_align(ui_InitPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InitPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InitPanel, lv_color_hex(0x071432), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InitPanel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InitPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_initMsg = lv_label_create(ui_InitPanel);
    lv_obj_set_width(ui_initMsg, 400);
    lv_obj_set_height(ui_initMsg, 100);
    lv_obj_set_align(ui_initMsg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_initMsg,
                      "If you can't connect to WiFi, please connect your computer or phone to the 'VolosWifiConf' WiFi network with the password 'password'");
    lv_obj_set_style_text_align(ui_initMsg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_initMsg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_choseNumbersPanel, ui_event_choseNumbersPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GOrULES, ui_event_GOrULES, LV_EVENT_ALL, NULL);

}
