// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel28 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel28, 175);
    lv_obj_set_height(ui_Panel28, 175);
    lv_obj_set_x(ui_Panel28, -178);
    lv_obj_set_y(ui_Panel28, 23);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel28, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel28, lv_color_hex(0x44CFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan1 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan1, 38);
    lv_obj_set_height(ui_numPan1, 38);
    lv_obj_set_x(ui_numPan1, -15);
    lv_obj_set_y(ui_numPan1, -15);
    lv_obj_clear_flag(ui_numPan1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan1, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH1 = lv_label_create(ui_numPan1);
    lv_obj_set_width(ui_myCH1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH1, "1");
    lv_obj_set_style_text_font(ui_myCH1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan2 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan2, 38);
    lv_obj_set_height(ui_numPan2, 38);
    lv_obj_set_x(ui_numPan2, 29);
    lv_obj_set_y(ui_numPan2, -15);
    lv_obj_clear_flag(ui_numPan2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan2, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH2 = lv_label_create(ui_numPan2);
    lv_obj_set_width(ui_myCH2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH2, "2");
    lv_obj_set_style_text_font(ui_myCH2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan3 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan3, 38);
    lv_obj_set_height(ui_numPan3, 38);
    lv_obj_set_x(ui_numPan3, 72);
    lv_obj_set_y(ui_numPan3, -15);
    lv_obj_clear_flag(ui_numPan3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan3, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH3 = lv_label_create(ui_numPan3);
    lv_obj_set_width(ui_myCH3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH3, "3");
    lv_obj_set_style_text_font(ui_myCH3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan4 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan4, 38);
    lv_obj_set_height(ui_numPan4, 38);
    lv_obj_set_x(ui_numPan4, 115);
    lv_obj_set_y(ui_numPan4, -15);
    lv_obj_clear_flag(ui_numPan4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan4, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH4 = lv_label_create(ui_numPan4);
    lv_obj_set_width(ui_myCH4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH4, "4");
    lv_obj_set_style_text_font(ui_myCH4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan5 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan5, 38);
    lv_obj_set_height(ui_numPan5, 38);
    lv_obj_set_x(ui_numPan5, -15);
    lv_obj_set_y(ui_numPan5, 29);
    lv_obj_clear_flag(ui_numPan5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan5, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH5 = lv_label_create(ui_numPan5);
    lv_obj_set_width(ui_myCH5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH5, "5");
    lv_obj_set_style_text_font(ui_myCH5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan6 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan6, 38);
    lv_obj_set_height(ui_numPan6, 38);
    lv_obj_set_x(ui_numPan6, 29);
    lv_obj_set_y(ui_numPan6, 29);
    lv_obj_clear_flag(ui_numPan6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan6, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH6 = lv_label_create(ui_numPan6);
    lv_obj_set_width(ui_myCH6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH6, "6");
    lv_obj_set_style_text_font(ui_myCH6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan7 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan7, 38);
    lv_obj_set_height(ui_numPan7, 38);
    lv_obj_set_x(ui_numPan7, 72);
    lv_obj_set_y(ui_numPan7, 29);
    lv_obj_clear_flag(ui_numPan7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan7, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH7 = lv_label_create(ui_numPan7);
    lv_obj_set_width(ui_myCH7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH7, "7");
    lv_obj_set_style_text_font(ui_myCH7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan8 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan8, 38);
    lv_obj_set_height(ui_numPan8, 38);
    lv_obj_set_x(ui_numPan8, 115);
    lv_obj_set_y(ui_numPan8, 29);
    lv_obj_clear_flag(ui_numPan8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan8, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH8 = lv_label_create(ui_numPan8);
    lv_obj_set_width(ui_myCH8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH8, "8");
    lv_obj_set_style_text_font(ui_myCH8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan9 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan9, 38);
    lv_obj_set_height(ui_numPan9, 38);
    lv_obj_set_x(ui_numPan9, -15);
    lv_obj_set_y(ui_numPan9, 73);
    lv_obj_clear_flag(ui_numPan9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan9, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH9 = lv_label_create(ui_numPan9);
    lv_obj_set_width(ui_myCH9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH9, "9");
    lv_obj_set_style_text_font(ui_myCH9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan10 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan10, 38);
    lv_obj_set_height(ui_numPan10, 38);
    lv_obj_set_x(ui_numPan10, 29);
    lv_obj_set_y(ui_numPan10, 73);
    lv_obj_clear_flag(ui_numPan10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan10, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH10 = lv_label_create(ui_numPan10);
    lv_obj_set_width(ui_myCH10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH10, "10");
    lv_obj_set_style_text_font(ui_myCH10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan11 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan11, 38);
    lv_obj_set_height(ui_numPan11, 38);
    lv_obj_set_x(ui_numPan11, 72);
    lv_obj_set_y(ui_numPan11, 73);
    lv_obj_clear_flag(ui_numPan11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan11, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan11, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH11 = lv_label_create(ui_numPan11);
    lv_obj_set_width(ui_myCH11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH11, "11");
    lv_obj_set_style_text_font(ui_myCH11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan12 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan12, 38);
    lv_obj_set_height(ui_numPan12, 38);
    lv_obj_set_x(ui_numPan12, 115);
    lv_obj_set_y(ui_numPan12, 73);
    lv_obj_clear_flag(ui_numPan12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan12, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan12, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH12 = lv_label_create(ui_numPan12);
    lv_obj_set_width(ui_myCH12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH12, "12");
    lv_obj_set_style_text_font(ui_myCH12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan13 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan13, 38);
    lv_obj_set_height(ui_numPan13, 38);
    lv_obj_set_x(ui_numPan13, -15);
    lv_obj_set_y(ui_numPan13, 117);
    lv_obj_clear_flag(ui_numPan13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan13, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan13, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH13 = lv_label_create(ui_numPan13);
    lv_obj_set_width(ui_myCH13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH13, "13");
    lv_obj_set_style_text_font(ui_myCH13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan14 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan14, 38);
    lv_obj_set_height(ui_numPan14, 38);
    lv_obj_set_x(ui_numPan14, 29);
    lv_obj_set_y(ui_numPan14, 117);
    lv_obj_clear_flag(ui_numPan14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan14, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan14, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH14 = lv_label_create(ui_numPan14);
    lv_obj_set_width(ui_myCH14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH14, "14");
    lv_obj_set_style_text_font(ui_myCH14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan15 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan15, 38);
    lv_obj_set_height(ui_numPan15, 38);
    lv_obj_set_x(ui_numPan15, 72);
    lv_obj_set_y(ui_numPan15, 117);
    lv_obj_clear_flag(ui_numPan15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan15, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH15 = lv_label_create(ui_numPan15);
    lv_obj_set_width(ui_myCH15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH15, "15");
    lv_obj_set_style_text_font(ui_myCH15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan16 = lv_obj_create(ui_Panel28);
    lv_obj_set_width(ui_numPan16, 38);
    lv_obj_set_height(ui_numPan16, 38);
    lv_obj_set_x(ui_numPan16, 115);
    lv_obj_set_y(ui_numPan16, 117);
    lv_obj_clear_flag(ui_numPan16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan16, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH16 = lv_label_create(ui_numPan16);
    lv_obj_set_width(ui_myCH16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH16, "16");
    lv_obj_set_style_text_font(ui_myCH16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel29, 175);
    lv_obj_set_height(ui_Panel29, 175);
    lv_obj_set_x(ui_Panel29, 0);
    lv_obj_set_y(ui_Panel29, 23);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel29, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel29, lv_color_hex(0x79118B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan17 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan17, 38);
    lv_obj_set_height(ui_numPan17, 38);
    lv_obj_set_x(ui_numPan17, -15);
    lv_obj_set_y(ui_numPan17, -15);
    lv_obj_clear_flag(ui_numPan17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan17, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan17, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH17 = lv_label_create(ui_numPan17);
    lv_obj_set_width(ui_myCH17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH17, "17");
    lv_obj_set_style_text_font(ui_myCH17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan18 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan18, 38);
    lv_obj_set_height(ui_numPan18, 38);
    lv_obj_set_x(ui_numPan18, 29);
    lv_obj_set_y(ui_numPan18, -15);
    lv_obj_clear_flag(ui_numPan18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan18, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan18, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH18 = lv_label_create(ui_numPan18);
    lv_obj_set_width(ui_myCH18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH18, "18");
    lv_obj_set_style_text_font(ui_myCH18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan19 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan19, 38);
    lv_obj_set_height(ui_numPan19, 38);
    lv_obj_set_x(ui_numPan19, 72);
    lv_obj_set_y(ui_numPan19, -15);
    lv_obj_clear_flag(ui_numPan19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan19, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan19, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH19 = lv_label_create(ui_numPan19);
    lv_obj_set_width(ui_myCH19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH19, "19");
    lv_obj_set_style_text_font(ui_myCH19, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan20 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan20, 38);
    lv_obj_set_height(ui_numPan20, 38);
    lv_obj_set_x(ui_numPan20, 115);
    lv_obj_set_y(ui_numPan20, -15);
    lv_obj_clear_flag(ui_numPan20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan20, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan20, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH20 = lv_label_create(ui_numPan20);
    lv_obj_set_width(ui_myCH20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH20, "20");
    lv_obj_set_style_text_font(ui_myCH20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan21 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan21, 38);
    lv_obj_set_height(ui_numPan21, 38);
    lv_obj_set_x(ui_numPan21, -15);
    lv_obj_set_y(ui_numPan21, 29);
    lv_obj_clear_flag(ui_numPan21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan21, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan21, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH21 = lv_label_create(ui_numPan21);
    lv_obj_set_width(ui_myCH21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH21, "21");
    lv_obj_set_style_text_font(ui_myCH21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan22 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan22, 38);
    lv_obj_set_height(ui_numPan22, 38);
    lv_obj_set_x(ui_numPan22, 29);
    lv_obj_set_y(ui_numPan22, 29);
    lv_obj_clear_flag(ui_numPan22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan22, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan22, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH22 = lv_label_create(ui_numPan22);
    lv_obj_set_width(ui_myCH22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH22, "22");
    lv_obj_set_style_text_font(ui_myCH22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan23 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan23, 38);
    lv_obj_set_height(ui_numPan23, 38);
    lv_obj_set_x(ui_numPan23, 72);
    lv_obj_set_y(ui_numPan23, 29);
    lv_obj_clear_flag(ui_numPan23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan23, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan23, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH23 = lv_label_create(ui_numPan23);
    lv_obj_set_width(ui_myCH23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH23, "23");
    lv_obj_set_style_text_font(ui_myCH23, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan24 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan24, 38);
    lv_obj_set_height(ui_numPan24, 38);
    lv_obj_set_x(ui_numPan24, 115);
    lv_obj_set_y(ui_numPan24, 29);
    lv_obj_clear_flag(ui_numPan24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan24, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan24, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH24 = lv_label_create(ui_numPan24);
    lv_obj_set_width(ui_myCH24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH24, "24");
    lv_obj_set_style_text_font(ui_myCH24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan25 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan25, 38);
    lv_obj_set_height(ui_numPan25, 38);
    lv_obj_set_x(ui_numPan25, -15);
    lv_obj_set_y(ui_numPan25, 73);
    lv_obj_clear_flag(ui_numPan25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan25, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan25, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan25, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH25 = lv_label_create(ui_numPan25);
    lv_obj_set_width(ui_myCH25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH25, "25");
    lv_obj_set_style_text_font(ui_myCH25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan26 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan26, 38);
    lv_obj_set_height(ui_numPan26, 38);
    lv_obj_set_x(ui_numPan26, 29);
    lv_obj_set_y(ui_numPan26, 73);
    lv_obj_clear_flag(ui_numPan26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan26, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan26, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan26, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH26 = lv_label_create(ui_numPan26);
    lv_obj_set_width(ui_myCH26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH26, "26");
    lv_obj_set_style_text_font(ui_myCH26, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan27 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan27, 38);
    lv_obj_set_height(ui_numPan27, 38);
    lv_obj_set_x(ui_numPan27, 72);
    lv_obj_set_y(ui_numPan27, 73);
    lv_obj_clear_flag(ui_numPan27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan27, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan27, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan27, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH27 = lv_label_create(ui_numPan27);
    lv_obj_set_width(ui_myCH27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH27, "27");
    lv_obj_set_style_text_font(ui_myCH27, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan28 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan28, 38);
    lv_obj_set_height(ui_numPan28, 38);
    lv_obj_set_x(ui_numPan28, 115);
    lv_obj_set_y(ui_numPan28, 73);
    lv_obj_clear_flag(ui_numPan28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan28, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan28, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan28, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH28 = lv_label_create(ui_numPan28);
    lv_obj_set_width(ui_myCH28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH28, "28");
    lv_obj_set_style_text_font(ui_myCH28, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan29 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan29, 38);
    lv_obj_set_height(ui_numPan29, 38);
    lv_obj_set_x(ui_numPan29, -15);
    lv_obj_set_y(ui_numPan29, 117);
    lv_obj_clear_flag(ui_numPan29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan29, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan29, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan29, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH29 = lv_label_create(ui_numPan29);
    lv_obj_set_width(ui_myCH29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH29, "29");
    lv_obj_set_style_text_font(ui_myCH29, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan30 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan30, 38);
    lv_obj_set_height(ui_numPan30, 38);
    lv_obj_set_x(ui_numPan30, 29);
    lv_obj_set_y(ui_numPan30, 117);
    lv_obj_clear_flag(ui_numPan30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan30, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan30, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH30 = lv_label_create(ui_numPan30);
    lv_obj_set_width(ui_myCH30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH30, "30");
    lv_obj_set_style_text_font(ui_myCH30, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan31 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan31, 38);
    lv_obj_set_height(ui_numPan31, 38);
    lv_obj_set_x(ui_numPan31, 72);
    lv_obj_set_y(ui_numPan31, 117);
    lv_obj_clear_flag(ui_numPan31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan31, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan31, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan31, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH31 = lv_label_create(ui_numPan31);
    lv_obj_set_width(ui_myCH31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH31, "31");
    lv_obj_set_style_text_font(ui_myCH31, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan32 = lv_obj_create(ui_Panel29);
    lv_obj_set_width(ui_numPan32, 38);
    lv_obj_set_height(ui_numPan32, 38);
    lv_obj_set_x(ui_numPan32, 115);
    lv_obj_set_y(ui_numPan32, 117);
    lv_obj_clear_flag(ui_numPan32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan32, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan32, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH32 = lv_label_create(ui_numPan32);
    lv_obj_set_width(ui_myCH32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH32, "32");
    lv_obj_set_style_text_font(ui_myCH32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel30, 175);
    lv_obj_set_height(ui_Panel30, 175);
    lv_obj_set_x(ui_Panel30, 177);
    lv_obj_set_y(ui_Panel30, 23);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel30, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel30, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel30, lv_color_hex(0x44CFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan33 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan33, 38);
    lv_obj_set_height(ui_numPan33, 38);
    lv_obj_set_x(ui_numPan33, -15);
    lv_obj_set_y(ui_numPan33, -15);
    lv_obj_clear_flag(ui_numPan33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan33, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan33, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan33, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH33 = lv_label_create(ui_numPan33);
    lv_obj_set_width(ui_myCH33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH33, "33");
    lv_obj_set_style_text_font(ui_myCH33, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan34 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan34, 38);
    lv_obj_set_height(ui_numPan34, 38);
    lv_obj_set_x(ui_numPan34, 29);
    lv_obj_set_y(ui_numPan34, -15);
    lv_obj_clear_flag(ui_numPan34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan34, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan34, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH34 = lv_label_create(ui_numPan34);
    lv_obj_set_width(ui_myCH34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH34, "34");
    lv_obj_set_style_text_font(ui_myCH34, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan35 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan35, 38);
    lv_obj_set_height(ui_numPan35, 38);
    lv_obj_set_x(ui_numPan35, 72);
    lv_obj_set_y(ui_numPan35, -15);
    lv_obj_clear_flag(ui_numPan35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan35, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan35, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH35 = lv_label_create(ui_numPan35);
    lv_obj_set_width(ui_myCH35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH35, "35");
    lv_obj_set_style_text_font(ui_myCH35, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan36 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan36, 38);
    lv_obj_set_height(ui_numPan36, 38);
    lv_obj_set_x(ui_numPan36, 115);
    lv_obj_set_y(ui_numPan36, -15);
    lv_obj_clear_flag(ui_numPan36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan36, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan36, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan36, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH36 = lv_label_create(ui_numPan36);
    lv_obj_set_width(ui_myCH36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH36, "36");
    lv_obj_set_style_text_font(ui_myCH36, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan37 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan37, 38);
    lv_obj_set_height(ui_numPan37, 38);
    lv_obj_set_x(ui_numPan37, -15);
    lv_obj_set_y(ui_numPan37, 29);
    lv_obj_clear_flag(ui_numPan37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan37, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan37, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH37 = lv_label_create(ui_numPan37);
    lv_obj_set_width(ui_myCH37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH37, "37");
    lv_obj_set_style_text_font(ui_myCH37, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan38 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan38, 38);
    lv_obj_set_height(ui_numPan38, 38);
    lv_obj_set_x(ui_numPan38, 29);
    lv_obj_set_y(ui_numPan38, 29);
    lv_obj_clear_flag(ui_numPan38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan38, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan38, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH38 = lv_label_create(ui_numPan38);
    lv_obj_set_width(ui_myCH38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH38, "38");
    lv_obj_set_style_text_font(ui_myCH38, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan39 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan39, 38);
    lv_obj_set_height(ui_numPan39, 38);
    lv_obj_set_x(ui_numPan39, 72);
    lv_obj_set_y(ui_numPan39, 29);
    lv_obj_clear_flag(ui_numPan39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan39, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan39, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan39, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH39 = lv_label_create(ui_numPan39);
    lv_obj_set_width(ui_myCH39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH39, "39");
    lv_obj_set_style_text_font(ui_myCH39, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan40 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan40, 38);
    lv_obj_set_height(ui_numPan40, 38);
    lv_obj_set_x(ui_numPan40, 115);
    lv_obj_set_y(ui_numPan40, 29);
    lv_obj_clear_flag(ui_numPan40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan40, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan40, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan40, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH40 = lv_label_create(ui_numPan40);
    lv_obj_set_width(ui_myCH40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH40, "40");
    lv_obj_set_style_text_font(ui_myCH40, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan41 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan41, 38);
    lv_obj_set_height(ui_numPan41, 38);
    lv_obj_set_x(ui_numPan41, -15);
    lv_obj_set_y(ui_numPan41, 73);
    lv_obj_clear_flag(ui_numPan41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan41, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan41, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan41, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan41, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH41 = lv_label_create(ui_numPan41);
    lv_obj_set_width(ui_myCH41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH41, "41");
    lv_obj_set_style_text_font(ui_myCH41, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan42 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan42, 38);
    lv_obj_set_height(ui_numPan42, 38);
    lv_obj_set_x(ui_numPan42, 29);
    lv_obj_set_y(ui_numPan42, 73);
    lv_obj_clear_flag(ui_numPan42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan42, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan42, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan42, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH42 = lv_label_create(ui_numPan42);
    lv_obj_set_width(ui_myCH42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH42, "42");
    lv_obj_set_style_text_font(ui_myCH42, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan43 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan43, 38);
    lv_obj_set_height(ui_numPan43, 38);
    lv_obj_set_x(ui_numPan43, 72);
    lv_obj_set_y(ui_numPan43, 73);
    lv_obj_clear_flag(ui_numPan43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan43, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan43, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan43, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH43 = lv_label_create(ui_numPan43);
    lv_obj_set_width(ui_myCH43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH43, "43");
    lv_obj_set_style_text_font(ui_myCH43, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan44 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan44, 38);
    lv_obj_set_height(ui_numPan44, 38);
    lv_obj_set_x(ui_numPan44, 115);
    lv_obj_set_y(ui_numPan44, 73);
    lv_obj_clear_flag(ui_numPan44, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan44, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan44, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan44, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH44 = lv_label_create(ui_numPan44);
    lv_obj_set_width(ui_myCH44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH44, "44");
    lv_obj_set_style_text_font(ui_myCH44, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan45 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan45, 38);
    lv_obj_set_height(ui_numPan45, 38);
    lv_obj_set_x(ui_numPan45, -15);
    lv_obj_set_y(ui_numPan45, 117);
    lv_obj_clear_flag(ui_numPan45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan45, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan45, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan45, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH45 = lv_label_create(ui_numPan45);
    lv_obj_set_width(ui_myCH45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH45, "45");
    lv_obj_set_style_text_font(ui_myCH45, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan46 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan46, 38);
    lv_obj_set_height(ui_numPan46, 38);
    lv_obj_set_x(ui_numPan46, 29);
    lv_obj_set_y(ui_numPan46, 117);
    lv_obj_clear_flag(ui_numPan46, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan46, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan46, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan46, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH46 = lv_label_create(ui_numPan46);
    lv_obj_set_width(ui_myCH46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH46, "46");
    lv_obj_set_style_text_font(ui_myCH46, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan47 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan47, 38);
    lv_obj_set_height(ui_numPan47, 38);
    lv_obj_set_x(ui_numPan47, 72);
    lv_obj_set_y(ui_numPan47, 117);
    lv_obj_clear_flag(ui_numPan47, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan47, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan47, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan47, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan47, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH47 = lv_label_create(ui_numPan47);
    lv_obj_set_width(ui_myCH47, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH47, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH47, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH47, "47");
    lv_obj_set_style_text_font(ui_myCH47, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_numPan48 = lv_obj_create(ui_Panel30);
    lv_obj_set_width(ui_numPan48, 38);
    lv_obj_set_height(ui_numPan48, 38);
    lv_obj_set_x(ui_numPan48, 115);
    lv_obj_set_y(ui_numPan48, 117);
    lv_obj_clear_flag(ui_numPan48, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_numPan48, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_numPan48, lv_color_hex(0x1B5187), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_numPan48, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_numPan48, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myCH48 = lv_label_create(ui_numPan48);
    lv_obj_set_width(ui_myCH48, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myCH48, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_myCH48, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myCH48, "48");
    lv_obj_set_style_text_font(ui_myCH48, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 95);
    lv_obj_set_height(ui_Button1, 39);
    lv_obj_set_x(ui_Button1, -207);
    lv_obj_set_y(ui_Button1, -92);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -206);
    lv_obj_set_y(ui_Label15, -91);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "BACK");

    ui_Button2 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 95);
    lv_obj_set_height(ui_Button2, 39);
    lv_obj_set_x(ui_Button2, 207);
    lv_obj_set_y(ui_Button2, -93);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 1);
    lv_obj_set_y(ui_Label16, -91);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Please chose seven numbers!");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 208);
    lv_obj_set_y(ui_Label17, -93);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "SAVE");

    lv_obj_add_event_cb(ui_numPan1, ui_event_numPan1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan2, ui_event_numPan2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan3, ui_event_numPan3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan4, ui_event_numPan4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan5, ui_event_numPan5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan6, ui_event_numPan6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan7, ui_event_numPan7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan8, ui_event_numPan8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan9, ui_event_numPan9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan10, ui_event_numPan10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan11, ui_event_numPan11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan12, ui_event_numPan12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan13, ui_event_numPan13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan14, ui_event_numPan14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan15, ui_event_numPan15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan16, ui_event_numPan16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan17, ui_event_numPan17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan18, ui_event_numPan18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan19, ui_event_numPan19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan20, ui_event_numPan20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan21, ui_event_numPan21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan22, ui_event_numPan22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan23, ui_event_numPan23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan24, ui_event_numPan24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan25, ui_event_numPan25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan26, ui_event_numPan26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan27, ui_event_numPan27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan28, ui_event_numPan28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan29, ui_event_numPan29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan30, ui_event_numPan30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan31, ui_event_numPan31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan32, ui_event_numPan32, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan33, ui_event_numPan33, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan34, ui_event_numPan34, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan35, ui_event_numPan35, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan36, ui_event_numPan36, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan37, ui_event_numPan37, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan38, ui_event_numPan38, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan39, ui_event_numPan39, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan40, ui_event_numPan40, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan41, ui_event_numPan41, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan42, ui_event_numPan42, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan43, ui_event_numPan43, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan44, ui_event_numPan44, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan45, ui_event_numPan45, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan46, ui_event_numPan46, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan47, ui_event_numPan47, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_numPan48, ui_event_numPan48, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
